language: ruby
rvm:
 - 2.4.1
services:
 - postgresql
before_script:
 - cp config/database.yml.travis config/database.yml
 - RAILS_ENV=test bundle exec rake db:create
deploy:
  provider: heroku
  api_key:
    secure: OA/X1KFWEON/zCPO07fb9jIb2RvyOCpEj84R93rOGEE4Gsog0CaYlAOnkXoHxgi1lE1SDgc45rFMwYArcV+FdTE3Clv7GlFCvRuTeuysHnqoxcQh1Vuddcs07tS9PyMUQUJdgGb1Lv8dpvgj+4Jvp2MeY732t3mpnLAmoE2Un3Ed7XbcgxGuU1/EAi8u22GCgaE3N+kw+lUAbdmIQEwR//S10xpTN5OamLmEX746uv2h7CNphCcOJnlfCxAC/QZytfO5dEhBsv3cepCuXsn4FByrnHgD/rGvHmfnRKAs75CAvakpwlhJ3i12H1VYMtrZ890uU3OLg/1h6ILnqn1AQLUP+31bIKs4Em38nj06BjvaQVwvsNlLscK5JwUCP8RO177S7cZROn34hDgpvtxFchjW3DEX2jBq26V5kHpcagvRDcsjozWOorAEkfpeEd8DShngo23HTxJtj7rx+MzGw1g2gHJ1ZPEu4p8T5BLpXsFkd4mFSduYN2vNAXiwqLOu2+dxNB96qgNSYjAqu2xBkEaOArauE6tmBa2vmMU8PoNzb0aJ+mSensV08TwZgRh+5mWcZje1OtAECMj15+vx1zDXH3fTPgFv1d8+de6Eo4kGIMNxcXIVkEzJjNhyhRFjW5LW11CjaDsdNYcwxIWLRJKstU6twzxpl9GBDa92Zwc=
  app: koroibos-jm
  on:
    repo: Jake0Miller/koroibos
